services:
  go-boilerplate:
    container_name: go-boilerplate
    build:
      context: .
      dockerfile: Dockerfile
    env_file: "./config/.env"
    depends_on:
      postgresdb:
        condition: service_healthy
    volumes:
      - ./data/logs:/app/data/logs
      - ./config/.env:/app/config/.env:ro
    networks:
      - go-boilerplate
    ports:
      - "8080:8080"
    restart: on-failure

  postgresdb:
    image: postgres:13.22-alpine3.22
    container_name: postgresdb
    restart: unless-stopped
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    networks:
      - go-boilerplate
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'" ]
      start_interval: 5s
      start_period: 10s
      interval: 15s
      timeout: 5s
      retries: 3

networks:
  go-boilerplate:
    driver: bridge

volumes:
  pg_data:
